In [1]:
import pandas as pd
import numpy as np
from dash import Dash , dcc , html , Input , Output, State
import dash_bootstrap_components as dbc
import plotly.express as px

In [2]:
app=Dash(__name__,external_stylesheets=[dbc.themes.BOOTSTRAP])

In [3]:
df_dev=pd.read_excel(r"C:\Users\utkar\Downloads\Developers.xlsx",index_col=[0])
df_exec=pd.read_excel(r"C:\Users\utkar\Downloads\Executives.xlsx",index_col=[0])

In [4]:
df_dev

,Position,Number of employees,Salary/month/employee,Salary/month,Salary/year/employee,Salary/year
0,Head Of Engineering,1,125000.00000,125000.00000,1500000,1500000
1,Backend Developer,2,115000.00000,230000.00000,1380000,2760000
2,Frontend Developer,2,90000.00000,180000.00000,1080000,2160000
3,QA Testers,1,35000.00000,35000.00000,420000,420000
4,Fresher - Team leader,2,41666.66667,83333.33333,500000,1000000
5,Fresher,4,27916.66667,111666.66670,335000,1340000
6,Interns,8,1000.00000,8000.00000,12000,96000

In [5]:
df_exec

,Position,Number of employees,Salary/month/employee,Salary/month,Salary/year/employee,Salary/year
0,Founder - CVO,1,50000,50000,600000,600000
1,CEO,1,50000,50000,600000,600000
2,Co-founder - COO,1,50000,50000,600000,600000

In [6]:
def compute_data_choice_1(df_exec):
    
    bar_data = df_exec
    pie_data= df_exec
    tree_data = df_exec
    return bar_data,tree_data, pie_data

In [7]:
def compute_data_choice_2(df_dev):
   
    bar_data = df_dev
    pie_data= df_dev
    tree_data = df_dev
    return bar_data,tree_data, pie_data

In [ ]:
exp_list= ['Salary/month/employee','Salary/month','Salary/year/employee','Salary/year']   #to give variable inputs 
 
app.layout = html.Div(children=[                                               #parent Division
    html.H1(' Ozibook Department wise Salary Expenditure',
            style={'text-align':'center',
                   'color':'#DE3163',
                   'font-size': 32}),
    html.H2('Executives & Developers Distribution',
            style={'text-align':'center',
                   'font-family':'verdana',
                   'text-color': 'cerise',
                   'font-size': 30}),
    html.H3('By Team-A',
            style={'text-align':'center',
                   'font-family':'verdana',
                   'text-color': 'cerise',
                   'font-size': 28}),
    html.Div([                                                        #Division for position dropdown                                  
      
        html.Div([
            html.Div([
                html.H2('Department:', style={
                    'margin-left': '1em','font-size':'20px'})
            ]
            ),
           
            dcc.Dropdown(id='ptype',
                         options=[
                             {'label': 'Executive',
                              'value': 'OPT1'},
                             {'label': 'Developer',
                              'value': 'OPT2'}
                         ],
                         placeholder='Select a report type',
                         style={'width': '80%', 'padding': '3px', 'font-size': '20px', 'text-align': 'center'})
            
        ], style={'display': 'flex'}),

      
    html.Div([                                                     #division for report type dropdown
            
            html.Div(
                [
                    html.H2('Salary Type:', style={
                        'margin-left': '1em','font-size':'20px'})
                ]
            ),
            dcc.Dropdown(id='etype',
                        
                         options=[
                             {'label': i, 'value': i} for i in exp_list],
                         placeholder="Expense type",
                         style={'width': '80%', 'padding': '3px', 'font-size': '20px', 'text-align-last': 'center'}),
           
        ], style={'display': 'flex'}),

    
    
    ]),
    
    
    
    
    html.Div([
        html.Div([], id='plot1',style={'border-style':'ridge','width':'50%'}), 
        html.Div([], id='plot2',style={'border-style':'ridge','width':'50%'})],
        style={'display': 'flex','border-style': 'ridge'}),                                    #Division for plots
    
    
    
    html.Div([html.Div([], id='plot3',style={'border-style':'ridge','width':'50%'}),   
 html.Div([
            html.H2('Yearly Salary of Departments'),
            html.H5('Calculate the salary spent per year on employees'),

            html.Br(),
            html.Br(),

            html.H4('Enter The Role: '),

            html.Br(),

            dcc.Dropdown(id='calc_dd', options=list(df_dev['Position']),
                         value=list([df_dev['Position']])[0], style={'width': '65%'}),
            
            html.Br(),
            html.Br(),

            html.H4('Enter the Number \n of Employees'),
            html.Br(),
            dcc.Input(id='calc_input', type="numbers", min=0, step=1, debounce=True, value=''),
            html.Br(),
            html.Br(),
            html.H4(id='calc_output')
        ])
        
                                                             
       ],style={'display':'flex','border-style': 'ridge'})                     #to put bottom rows plots and cal side by side

   

    ],style={'background-color':'powderblue'})                                 #for background color


@app.callback(
    [Output(component_id='plot1', component_property='children'),
                Output(component_id='plot2', component_property='children'),
                Output(component_id='plot3', component_property='children')],
               [Input(component_id='ptype', component_property='value'),
                Input(component_id='etype', component_property='value')],
               [State("plot1", 'children'), State("plot2", "children"),
                State("plot3", "children")])

def get_graph(chart, inp, c1,c2,c3):                                    #callback for graph           
      
        if chart == 'OPT1':
            bar_data, tree_data, pie_data = compute_data_choice_1(df_exec)
            
           
            bar_fig = px.bar(bar_data, x='Position', y=inp, title='Dept. Salary in Amount')
            
            
            pie_fig = px.pie(pie_data, values=inp, names='Position',hole= 0.4, title='Expenditure Share')
            
           
            tree_fig = px.treemap(tree_data, path=['Position', inp], 
                      values= inp ,
                    
                      color_continuous_scale='RdBu',
                      title='Structure of the Department'
                )
            
            
          
            return [dcc.Graph(figure=tree_fig), 
                    dcc.Graph(figure=pie_fig),
                    dcc.Graph(figure=bar_fig),
                   ]
        else:
            bar_data, tree_data, pie_data = compute_data_choice_2(df_dev)
            
           
            bar_fig = px.bar(bar_data, x='Position', y=inp, title='Dept. Salary in Amount')
            
            
            pie_fig = px.pie(pie_data, values=inp, names='Position', hole=0.5,title='Expenditure Share')
            
            tree_fig = px.treemap(tree_data, path=['Position', inp], 
                      values= inp ,
                    
                      color_continuous_scale='RdBu',
                      title='Structure of the Department'
                )
            
            return [dcc.Graph(figure=tree_fig), 
                    dcc.Graph(figure=pie_fig),
                    dcc.Graph(figure=bar_fig),
                   ]
                                                                                #callback for calculator
@app.callback(
    Output('calc_output', 'children'),
    [
        Input('calc_dd', 'value'),
        Input('calc_input', 'value')]
)
def calc(calc_dd_value, calc_input_value):
    print(calc_dd_value)
    print(type(calc_dd_value))
    print(calc_input_value)
    calc_input_value = int(calc_input_value)
    print(type(calc_input_value))

    dff = df_dev[df_dev['Position'] == calc_dd_value]
    tot_sal = int(dff['Salary/year/employee']) * calc_input_value
    tot_sal = "{:,}".format(tot_sal)
    return f'The total salary spent for {calc_input_value} {calc_dd_value} yearly is \n{tot_sal}'



if __name__ == '__main__':
    app.run_server(port=8002)

Dash is running on http://127.0.0.1:8002/

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off

 * Running on http://127.0.0.1:8002/ (Press CTRL+C to quit)
127.0.0.1 - - [02/Dec/2022 19:06:12] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [02/Dec/2022 19:06:12] "GET /_dash-dependencies HTTP/1.1" 200 -
127.0.0.1 - - [02/Dec/2022 19:06:12] "GET /_dash-layout HTTP/1.1" 200 -
127.0.0.1 - - [02/Dec/2022 19:06:13] "GET /_dash-component-suites/dash/dcc/async-dropdown.js HTTP/1.1" 200 -

['Head Of Engineering ', 'Backend Developer', 'Frontend Developer', 'QA Testers ', 'Fresher - Team leader ', 'Fresher', 'Interns']
<class 'list'>

Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "C:\Users\utkar\anaconda3\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\utkar\anaconda3\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\utkar\anaconda3\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\utkar\anaconda3\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\utkar\anaconda3\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\utkar\anaconda3\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\utkar\anaconda3\lib\site-packages\dash\dash.py", line 1274, in dispatch
    ctx.run(
  File "C:\Users\utkar\anaconda3\lib\site-packages\dash\_callback.py", line 440, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
  File "<ipython-input-8-92bcb6736165>", line 170, in calc
    calc_input_value = int(calc_input_value)
ValueError: invalid literal for int() with base 10: ''

127.0.0.1 - - [02/Dec/2022 19:06:13] "POST /_dash-update-component HTTP/1.1" 500 -

Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "C:\Users\utkar\anaconda3\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\utkar\anaconda3\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\utkar\anaconda3\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\utkar\anaconda3\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\utkar\anaconda3\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\utkar\anaconda3\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\utkar\anaconda3\lib\site-packages\dash\dash.py", line 1274, in dispatch
    ctx.run(
  File "C:\Users\utkar\anaconda3\lib\site-packages\dash\_callback.py", line 440, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
  File "<ipython-input-8-92bcb6736165>", line 148, in get_graph
    tree_fig = px.treemap(tree_data, path=['Position', inp],
  File "C:\Users\utkar\anaconda3\lib\site-packages\plotly\express\_chart_types.py", line 1591, in treemap
    return make_figure(
  File "C:\Users\utkar\anaconda3\lib\site-packages\plotly\express\_core.py", line 1992, in make_figure
    args = process_dataframe_hierarchy(args)
  File "C:\Users\utkar\anaconda3\lib\site-packages\plotly\express\_core.py", line 1545, in process_dataframe_hierarchy
    _check_dataframe_all_leaves(df[path[::-1]])
  File "C:\Users\utkar\anaconda3\lib\site-packages\pandas\core\frame.py", line 2908, in __getitem__
    indexer = self.loc._get_listlike_indexer(key, axis=1, raise_missing=True)[1]
  File "C:\Users\utkar\anaconda3\lib\site-packages\pandas\core\indexing.py", line 1254, in _get_listlike_indexer
    self._validate_read_indexer(keyarr, indexer, axis, raise_missing=raise_missing)
  File "C:\Users\utkar\anaconda3\lib\site-packages\pandas\core\indexing.py", line 1304, in _validate_read_indexer
    raise KeyError(f"{not_found} not in index")
KeyError: '[None] not in index'

127.0.0.1 - - [02/Dec/2022 19:06:14] "POST /_dash-update-component HTTP/1.1" 500 -

Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "C:\Users\utkar\anaconda3\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\utkar\anaconda3\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\utkar\anaconda3\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\utkar\anaconda3\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\utkar\anaconda3\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\utkar\anaconda3\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\utkar\anaconda3\lib\site-packages\dash\dash.py", line 1274, in dispatch
    ctx.run(
  File "C:\Users\utkar\anaconda3\lib\site-packages\dash\_callback.py", line 440, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
  File "<ipython-input-8-92bcb6736165>", line 148, in get_graph
    tree_fig = px.treemap(tree_data, path=['Position', inp],
  File "C:\Users\utkar\anaconda3\lib\site-packages\plotly\express\_chart_types.py", line 1591, in treemap
    return make_figure(
  File "C:\Users\utkar\anaconda3\lib\site-packages\plotly\express\_core.py", line 1992, in make_figure
    args = process_dataframe_hierarchy(args)
  File "C:\Users\utkar\anaconda3\lib\site-packages\plotly\express\_core.py", line 1545, in process_dataframe_hierarchy
    _check_dataframe_all_leaves(df[path[::-1]])
  File "C:\Users\utkar\anaconda3\lib\site-packages\pandas\core\frame.py", line 2908, in __getitem__
    indexer = self.loc._get_listlike_indexer(key, axis=1, raise_missing=True)[1]
  File "C:\Users\utkar\anaconda3\lib\site-packages\pandas\core\indexing.py", line 1254, in _get_listlike_indexer
    self._validate_read_indexer(keyarr, indexer, axis, raise_missing=raise_missing)
  File "C:\Users\utkar\anaconda3\lib\site-packages\pandas\core\indexing.py", line 1304, in _validate_read_indexer
    raise KeyError(f"{not_found} not in index")
KeyError: '[None] not in index'

127.0.0.1 - - [02/Dec/2022 19:06:16] "POST /_dash-update-component HTTP/1.1" 500 -
127.0.0.1 - - [02/Dec/2022 19:06:18] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [02/Dec/2022 19:06:18] "GET /_dash-component-suites/dash/dcc/async-graph.js HTTP/1.1" 200 -
127.0.0.1 - - [02/Dec/2022 19:06:18] "GET /_dash-component-suites/dash/dcc/async-plotlyjs.js HTTP/1.1" 200 -